CREATE TABLE CLIENTS (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(75) NOT NULL,
    LASTNAME VARCHAR(75) NOT NULL,
    DOCNUMBER VARCHAR(11) NOT NULL
);

CREATE TABLE PRODUCTS (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION VARCHAR(150) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    STOCK INT NOT NULL,
    PRICE DOUBLE NOT NULL
);

CREATE TABLE INVOICE (
    id INT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID BIGINT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    TOTAL DOUBLE NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(id)
);


CREATE TABLE INVOICE_DETAILS (
    invoice_detail_id INT PRIMARY KEY AUTO_INCREMENT,
    INVOICE_ID INT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    AMOUNT INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(id),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(id)
);

